//
// AppClipAdvancedExperiencesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppClipAdvancedExperiencesResponse: Codable {

    public var data: [AppClipAdvancedExperience]
    public var included: [OneOfAppClipAdvancedExperiencesResponseIncludedItems]?
    public var links: PagedDocumentLinks
    public var meta: PagingInformation?

    public init(data: [AppClipAdvancedExperience], included: [OneOfAppClipAdvancedExperiencesResponseIncludedItems]? = nil, links: PagedDocumentLinks, meta: PagingInformation? = nil) {
        self.data = data
        self.included = included
        self.links = links
        self.meta = meta
    }


}
