//
// AppClipAppStoreReviewDetailCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppClipAppStoreReviewDetailCreateRequest: Codable {

    public var data: AppClipAppStoreReviewDetailCreateRequestData

    public init(data: AppClipAppStoreReviewDetailCreateRequestData) {
        self.data = data
    }


}
