//
// AppClipDefaultExperienceCreateRequestDataRelationshipsAppClipDefaultExperienceTemplate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppClipDefaultExperienceCreateRequestDataRelationshipsAppClipDefaultExperienceTemplate: Codable {

    public var data: AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceData?

    public init(data: AppClipAppStoreReviewDetailRelationshipsAppClipDefaultExperienceData? = nil) {
        self.data = data
    }


}
