//
// AppClipAdvancedExperienceRelationshipsHeaderImage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppClipAdvancedExperienceRelationshipsHeaderImage: Codable {

    public var links: AppCategoryRelationshipsSubcategoriesLinks?
    public var data: AppClipAdvancedExperienceRelationshipsHeaderImageData?

    public init(links: AppCategoryRelationshipsSubcategoriesLinks? = nil, data: AppClipAdvancedExperienceRelationshipsHeaderImageData? = nil) {
        self.links = links
        self.data = data
    }


}
