//
// AppClipAdvancedExperienceImageCreateRequestData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppClipAdvancedExperienceImageCreateRequestData: Codable {

    public enum ModelType: String, Codable { 
        case appclipadvancedexperienceimages = "appClipAdvancedExperienceImages"
    }
    public var type: ModelType
    public var attributes: AppClipAdvancedExperienceImageCreateRequestDataAttributes

    public init(type: ModelType, attributes: AppClipAdvancedExperienceImageCreateRequestDataAttributes) {
        self.type = type
        self.attributes = attributes
    }


}
