//
// AppClipDomainStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppClipDomainStatusResponse: Codable {

    public var data: AppClipDomainStatus
    public var links: DocumentLinks

    public init(data: AppClipDomainStatus, links: DocumentLinks) {
        self.data = data
        self.links = links
    }


}
