//
// AppEncryptionDeclarationAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppEncryptionDeclarationAttributes: Codable {

    public var usesEncryption: Bool?
    public var exempt: Bool?
    public var containsProprietaryCryptography: Bool?
    public var containsThirdPartyCryptography: Bool?
    public var availableOnFrenchStore: Bool?
    public var platform: Platform?
    public var uploadedDate: Date?
    public var documentUrl: String?
    public var documentName: String?
    public var documentType: String?
    public var appEncryptionDeclarationState: AppEncryptionDeclarationState?
    public var codeValue: String?

    public init(usesEncryption: Bool? = nil, exempt: Bool? = nil, containsProprietaryCryptography: Bool? = nil, containsThirdPartyCryptography: Bool? = nil, availableOnFrenchStore: Bool? = nil, platform: Platform? = nil, uploadedDate: Date? = nil, documentUrl: String? = nil, documentName: String? = nil, documentType: String? = nil, appEncryptionDeclarationState: AppEncryptionDeclarationState? = nil, codeValue: String? = nil) {
        self.usesEncryption = usesEncryption
        self.exempt = exempt
        self.containsProprietaryCryptography = containsProprietaryCryptography
        self.containsThirdPartyCryptography = containsThirdPartyCryptography
        self.availableOnFrenchStore = availableOnFrenchStore
        self.platform = platform
        self.uploadedDate = uploadedDate
        self.documentUrl = documentUrl
        self.documentName = documentName
        self.documentType = documentType
        self.appEncryptionDeclarationState = appEncryptionDeclarationState
        self.codeValue = codeValue
    }


}
