//
// AppEncryptionDeclarationRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppEncryptionDeclarationRelationships: Codable {

    public var app: AppClipRelationshipsApp?

    public init(app: AppClipRelationshipsApp? = nil) {
        self.app = app
    }


}
