//
// AppEventVideoClipCreateRequestData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppEventVideoClipCreateRequestData: Codable {

    public enum ModelType: String, Codable { 
        case appeventvideoclips = "appEventVideoClips"
    }
    public var type: ModelType
    public var attributes: AppEventVideoClipCreateRequestDataAttributes
    public var relationships: AppEventScreenshotCreateRequestDataRelationships

    public init(type: ModelType, attributes: AppEventVideoClipCreateRequestDataAttributes, relationships: AppEventScreenshotCreateRequestDataRelationships) {
        self.type = type
        self.attributes = attributes
        self.relationships = relationships
    }


}
