//
// AppInfoLocalizationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppInfoLocalizationResponse: Codable {

    public var data: AppInfoLocalization
    public var included: [AppInfo]?
    public var links: DocumentLinks

    public init(data: AppInfoLocalization, included: [AppInfo]? = nil, links: DocumentLinks) {
        self.data = data
        self.included = included
        self.links = links
    }


}
