//
// AppInfoUpdateRequestDataRelationshipsPrimaryCategory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppInfoUpdateRequestDataRelationshipsPrimaryCategory: Codable {

    public var data: AppCategoryRelationshipsSubcategoriesData?

    public init(data: AppCategoryRelationshipsSubcategoriesData? = nil) {
        self.data = data
    }


}
