//
// AppPreviewSetCreateRequestDataRelationshipsAppCustomProductPageLocalization.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppPreviewSetCreateRequestDataRelationshipsAppCustomProductPageLocalization: Codable {

    public var data: AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsData?

    public init(data: AppCustomProductPageVersionRelationshipsAppCustomProductPageLocalizationsData? = nil) {
        self.data = data
    }


}
