//
// AppPreviewSetAppPreviewsLinkagesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppPreviewSetAppPreviewsLinkagesRequest: Codable {

    public var data: [AppPreviewSetRelationshipsAppPreviewsData]

    public init(data: [AppPreviewSetRelationshipsAppPreviewsData]) {
        self.data = data
    }


}
