//
// AppPreviewCreateRequestDataRelationshipsAppPreviewSet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppPreviewCreateRequestDataRelationshipsAppPreviewSet: Codable {

    public var data: AppCustomProductPageLocalizationRelationshipsAppPreviewSetsData

    public init(data: AppCustomProductPageLocalizationRelationshipsAppPreviewSetsData) {
        self.data = data
    }


}
