//
// AppRelationshipsCiProduct.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppRelationshipsCiProduct: Codable {

    public var links: AppCategoryRelationshipsSubcategoriesLinks?
    public var data: AppRelationshipsCiProductData?

    public init(links: AppCategoryRelationshipsSubcategoriesLinks? = nil, data: AppRelationshipsCiProductData? = nil) {
        self.links = links
        self.data = data
    }


}
