//
// AppStoreVersionRelationshipsBuild.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppStoreVersionRelationshipsBuild: Codable {

    public var links: AppCategoryRelationshipsSubcategoriesLinks?
    public var data: AppStoreVersionRelationshipsBuildData?

    public init(links: AppCategoryRelationshipsSubcategoriesLinks? = nil, data: AppStoreVersionRelationshipsBuildData? = nil) {
        self.links = links
        self.data = data
    }


}
