//
// AppScreenshotAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppScreenshotAttributes: Codable {

    public var fileSize: Int?
    public var fileName: String?
    public var sourceFileChecksum: String?
    public var imageAsset: ImageAsset?
    public var assetToken: String?
    public var assetType: String?
    public var uploadOperations: [UploadOperation]?
    public var assetDeliveryState: AppMediaAssetState?

    public init(fileSize: Int? = nil, fileName: String? = nil, sourceFileChecksum: String? = nil, imageAsset: ImageAsset? = nil, assetToken: String? = nil, assetType: String? = nil, uploadOperations: [UploadOperation]? = nil, assetDeliveryState: AppMediaAssetState? = nil) {
        self.fileSize = fileSize
        self.fileName = fileName
        self.sourceFileChecksum = sourceFileChecksum
        self.imageAsset = imageAsset
        self.assetToken = assetToken
        self.assetType = assetType
        self.uploadOperations = uploadOperations
        self.assetDeliveryState = assetDeliveryState
    }


}
