//
// AppStoreReviewDetailRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppStoreReviewDetailRelationships: Codable {

    public var appStoreVersion: AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion?
    public var appStoreReviewAttachments: AppStoreReviewDetailRelationshipsAppStoreReviewAttachments?

    public init(appStoreVersion: AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion? = nil, appStoreReviewAttachments: AppStoreReviewDetailRelationshipsAppStoreReviewAttachments? = nil) {
        self.appStoreVersion = appStoreVersion
        self.appStoreReviewAttachments = appStoreReviewAttachments
    }


}
