//
// AppStoreVersionExperimentTreatmentLocalizationRelationshipsAppStoreVersionExperimentTreatment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppStoreVersionExperimentTreatmentLocalizationRelationshipsAppStoreVersionExperimentTreatment: Codable {

    public var links: AppCategoryRelationshipsSubcategoriesLinks?
    public var data: AppStoreVersionExperimentTreatmentLocalizationRelationshipsAppStoreVersionExperimentTreatmentData?

    public init(links: AppCategoryRelationshipsSubcategoriesLinks? = nil, data: AppStoreVersionExperimentTreatmentLocalizationRelationshipsAppStoreVersionExperimentTreatmentData? = nil) {
        self.links = links
        self.data = data
    }


}
