//
// AppStoreVersionExperimentTreatmentCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppStoreVersionExperimentTreatmentCreateRequest: Codable {

    public var data: AppStoreVersionExperimentTreatmentCreateRequestData

    public init(data: AppStoreVersionExperimentTreatmentCreateRequestData) {
        self.data = data
    }


}
