//
// AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment: Codable {

    public var links: AppCategoryRelationshipsSubcategoriesLinks?
    public var data: AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentData?

    public init(links: AppCategoryRelationshipsSubcategoriesLinks? = nil, data: AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentData? = nil) {
        self.links = links
        self.data = data
    }


}
