//
// AppStoreVersionPhasedReleaseCreateRequestDataAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppStoreVersionPhasedReleaseCreateRequestDataAttributes: Codable {

    public var phasedReleaseState: PhasedReleaseState?

    public init(phasedReleaseState: PhasedReleaseState? = nil) {
        self.phasedReleaseState = phasedReleaseState
    }


}
