//
// AppScreenshotResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppScreenshotResponse: Codable {

    public var data: AppScreenshot
    public var included: [AppScreenshotSet]?
    public var links: DocumentLinks

    public init(data: AppScreenshot, included: [AppScreenshotSet]? = nil, links: DocumentLinks) {
        self.data = data
        self.included = included
        self.links = links
    }


}
