//
// AppScreenshotSetRelationshipsAppScreenshots.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppScreenshotSetRelationshipsAppScreenshots: Codable {

    public var links: AppCategoryRelationshipsSubcategoriesLinks?
    public var meta: PagingInformation?
    public var data: [AppScreenshotSetRelationshipsAppScreenshotsData]?

    public init(links: AppCategoryRelationshipsSubcategoriesLinks? = nil, meta: PagingInformation? = nil, data: [AppScreenshotSetRelationshipsAppScreenshotsData]? = nil) {
        self.links = links
        self.meta = meta
        self.data = data
    }


}
