//
// AppScreenshotRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppScreenshotRelationships: Codable {

    public var appScreenshotSet: AppScreenshotRelationshipsAppScreenshotSet?

    public init(appScreenshotSet: AppScreenshotRelationshipsAppScreenshotSet? = nil) {
        self.appScreenshotSet = appScreenshotSet
    }


}
