//
// AppStoreVersionCreateRequestData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppStoreVersionCreateRequestData: Codable {

    public enum ModelType: String, Codable { 
        case appstoreversions = "appStoreVersions"
    }
    public var type: ModelType
    public var attributes: AppStoreVersionCreateRequestDataAttributes
    public var relationships: AppStoreVersionCreateRequestDataRelationships

    public init(type: ModelType, attributes: AppStoreVersionCreateRequestDataAttributes, relationships: AppStoreVersionCreateRequestDataRelationships) {
        self.type = type
        self.attributes = attributes
        self.relationships = relationships
    }


}
