//
// AppScreenshotCreateRequestData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppScreenshotCreateRequestData: Codable {

    public enum ModelType: String, Codable { 
        case appscreenshots = "appScreenshots"
    }
    public var type: ModelType
    public var attributes: AppClipAdvancedExperienceImageCreateRequestDataAttributes
    public var relationships: AppScreenshotCreateRequestDataRelationships

    public init(type: ModelType, attributes: AppClipAdvancedExperienceImageCreateRequestDataAttributes, relationships: AppScreenshotCreateRequestDataRelationships) {
        self.type = type
        self.attributes = attributes
        self.relationships = relationships
    }


}
