//
// BetaAppClipInvocationLocalizationCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BetaAppClipInvocationLocalizationCreateRequest: Codable {

    public var data: BetaAppClipInvocationLocalizationCreateRequestData

    public init(data: BetaAppClipInvocationLocalizationCreateRequestData) {
        self.data = data
    }


}
