//
// BetaAppClipInvocationLocalizationUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BetaAppClipInvocationLocalizationUpdateRequest: Codable {

    public var data: BetaAppClipInvocationLocalizationUpdateRequestData

    public init(data: BetaAppClipInvocationLocalizationUpdateRequestData) {
        self.data = data
    }


}
