//
// BetaLicenseAgreementAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BetaLicenseAgreementAttributes: Codable {

    public var agreementText: String?

    public init(agreementText: String? = nil) {
        self.agreementText = agreementText
    }


}
