//
// BetaAppClipInvocationLocalizationCreateRequestDataRelationshipsBetaAppClipInvocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BetaAppClipInvocationLocalizationCreateRequestDataRelationshipsBetaAppClipInvocation: Codable {

    public var data: BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData

    public init(data: BetaAppClipInvocationLocalizationInlineCreateRelationshipsBetaAppClipInvocationData) {
        self.data = data
    }


}
