//
// BuildUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuildUpdateRequest: Codable {

    public var data: BuildUpdateRequestData

    public init(data: BuildUpdateRequestData) {
        self.data = data
    }


}
