//
// BuildBetaGroupsLinkagesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuildBetaGroupsLinkagesRequest: Codable {

    public var data: [AppRelationshipsBetaGroupsData]

    public init(data: [AppRelationshipsBetaGroupsData]) {
        self.data = data
    }


}
