//
// BuildUpdateRequestDataRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuildUpdateRequestDataRelationships: Codable {

    public var appEncryptionDeclaration: BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration?

    public init(appEncryptionDeclaration: BuildUpdateRequestDataRelationshipsAppEncryptionDeclaration? = nil) {
        self.appEncryptionDeclaration = appEncryptionDeclaration
    }


}
