//
// BuildAppEncryptionDeclarationLinkageResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuildAppEncryptionDeclarationLinkageResponse: Codable {

    public var data: BuildRelationshipsAppEncryptionDeclarationData
    public var links: DocumentLinks

    public init(data: BuildRelationshipsAppEncryptionDeclarationData, links: DocumentLinks) {
        self.data = data
        self.links = links
    }


}
