//
// BundleIdUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BundleIdUpdateRequest: Codable {

    public var data: BundleIdUpdateRequestData

    public init(data: BundleIdUpdateRequestData) {
        self.data = data
    }


}
