//
// CiBuildActionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CiBuildActionResponse: Codable {

    public var data: CiBuildAction
    public var included: [CiBuildRun]?
    public var links: DocumentLinks

    public init(data: CiBuildAction, included: [CiBuildRun]? = nil, links: DocumentLinks) {
        self.data = data
        self.included = included
        self.links = links
    }


}
