//
// CiBuildRunCreateRequestData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CiBuildRunCreateRequestData: Codable {

    public enum ModelType: String, Codable { 
        case cibuildruns = "ciBuildRuns"
    }
    public var type: ModelType
    public var attributes: CiBuildRunCreateRequestDataAttributes?
    public var relationships: CiBuildRunCreateRequestDataRelationships?

    public init(type: ModelType, attributes: CiBuildRunCreateRequestDataAttributes? = nil, relationships: CiBuildRunCreateRequestDataRelationships? = nil) {
        self.type = type
        self.attributes = attributes
        self.relationships = relationships
    }


}
