//
// CiMacOsVersionRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CiMacOsVersionRelationships: Codable {

    public var xcodeVersions: CiMacOsVersionRelationshipsXcodeVersions?

    public init(xcodeVersions: CiMacOsVersionRelationshipsXcodeVersions? = nil) {
        self.xcodeVersions = xcodeVersions
    }


}
