//
// CiProductRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CiProductRelationships: Codable {

    public var app: AppClipRelationshipsApp?
    public var bundleId: CiProductRelationshipsBundleId?
    public var primaryRepositories: CiProductRelationshipsPrimaryRepositories?

    public init(app: AppClipRelationshipsApp? = nil, bundleId: CiProductRelationshipsBundleId? = nil, primaryRepositories: CiProductRelationshipsPrimaryRepositories? = nil) {
        self.app = app
        self.bundleId = bundleId
        self.primaryRepositories = primaryRepositories
    }


}
