//
// CiTestResultResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CiTestResultResponse: Codable {

    public var data: CiTestResult
    public var links: DocumentLinks

    public init(data: CiTestResult, links: DocumentLinks) {
        self.data = data
        self.links = links
    }


}
