//
// CiWorkflowUpdateRequestData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CiWorkflowUpdateRequestData: Codable {

    public enum ModelType: String, Codable { 
        case ciworkflows = "ciWorkflows"
    }
    public var type: ModelType
    public var _id: String
    public var attributes: CiWorkflowUpdateRequestDataAttributes?
    public var relationships: CiWorkflowUpdateRequestDataRelationships?

    public init(type: ModelType, _id: String, attributes: CiWorkflowUpdateRequestDataAttributes? = nil, relationships: CiWorkflowUpdateRequestDataRelationships? = nil) {
        self.type = type
        self._id = _id
        self.attributes = attributes
        self.relationships = relationships
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case attributes
        case relationships
    }

}
