//
// CiWorkflowCreateRequestDataRelationshipsXcodeVersion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CiWorkflowCreateRequestDataRelationshipsXcodeVersion: Codable {

    public var data: CiMacOsVersionRelationshipsXcodeVersionsData

    public init(data: CiMacOsVersionRelationshipsXcodeVersionsData) {
        self.data = data
    }


}
