//
// DiagnosticLogsProductData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DiagnosticLogsProductData: Codable {

    public var signatureId: String?
    public var diagnosticInsights: [DiagnosticLogsDiagnosticInsights]?
    public var diagnosticLogs: [DiagnosticLogsDiagnosticLogs]?

    public init(signatureId: String? = nil, diagnosticInsights: [DiagnosticLogsDiagnosticInsights]? = nil, diagnosticLogs: [DiagnosticLogsDiagnosticLogs]? = nil) {
        self.signatureId = signatureId
        self.diagnosticInsights = diagnosticInsights
        self.diagnosticLogs = diagnosticLogs
    }


}
