//
// ErrorSourcePointer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ErrorSourcePointer: Codable {

    public var pointer: String?

    public init(pointer: String? = nil) {
        self.pointer = pointer
    }


}
