//
// GameCenterEnabledVersionsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GameCenterEnabledVersionsResponse: Codable {

    public var data: [GameCenterEnabledVersion]
    public var included: [OneOfGameCenterEnabledVersionsResponseIncludedItems]?
    public var links: PagedDocumentLinks
    public var meta: PagingInformation?

    public init(data: [GameCenterEnabledVersion], included: [OneOfGameCenterEnabledVersionsResponseIncludedItems]? = nil, links: PagedDocumentLinks, meta: PagingInformation? = nil) {
        self.data = data
        self.included = included
        self.links = links
        self.meta = meta
    }


}
