//
// InAppPurchasePriceInlineCreateRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InAppPurchasePriceInlineCreateRelationships: Codable {

    public var inAppPurchaseV2: InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2?
    public var inAppPurchasePricePoint: InAppPurchasePriceInlineCreateRelationshipsInAppPurchasePricePoint?

    public init(inAppPurchaseV2: InAppPurchasePriceInlineCreateRelationshipsInAppPurchaseV2? = nil, inAppPurchasePricePoint: InAppPurchasePriceInlineCreateRelationshipsInAppPurchasePricePoint? = nil) {
        self.inAppPurchaseV2 = inAppPurchaseV2
        self.inAppPurchasePricePoint = inAppPurchasePricePoint
    }


}
