//
// PromotedPurchaseUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PromotedPurchaseUpdateRequest: Codable {

    public var data: PromotedPurchaseUpdateRequestData

    public init(data: PromotedPurchaseUpdateRequestData) {
        self.data = data
    }


}
