//
// ReviewSubmissionCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReviewSubmissionCreateRequest: Codable {

    public var data: ReviewSubmissionCreateRequestData

    public init(data: ReviewSubmissionCreateRequestData) {
        self.data = data
    }


}
