//
// ReviewSubmissionUpdateRequestDataAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReviewSubmissionUpdateRequestDataAttributes: Codable {

    public var submitted: Bool?
    public var canceled: Bool?

    public init(submitted: Bool? = nil, canceled: Bool? = nil) {
        self.submitted = submitted
        self.canceled = canceled
    }


}
