//
// ReviewSubmissionItemResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReviewSubmissionItemResponse: Codable {

    public var data: ReviewSubmissionItem
    public var included: [OneOfReviewSubmissionItemResponseIncludedItems]?
    public var links: DocumentLinks

    public init(data: ReviewSubmissionItem, included: [OneOfReviewSubmissionItemResponseIncludedItems]? = nil, links: DocumentLinks) {
        self.data = data
        self.included = included
        self.links = links
    }


}
