//
// ReviewSubmissionItemCreateRequestDataRelationshipsReviewSubmission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReviewSubmissionItemCreateRequestDataRelationshipsReviewSubmission: Codable {

    public var data: AppRelationshipsReviewSubmissionsData

    public init(data: AppRelationshipsReviewSubmissionsData) {
        self.data = data
    }


}
