//
// ReviewSubmissionItemCreateRequestData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ReviewSubmissionItemCreateRequestData: Codable {

    public enum ModelType: String, Codable { 
        case reviewsubmissionitems = "reviewSubmissionItems"
    }
    public var type: ModelType
    public var relationships: ReviewSubmissionItemCreateRequestDataRelationships

    public init(type: ModelType, relationships: ReviewSubmissionItemCreateRequestDataRelationships) {
        self.type = type
        self.relationships = relationships
    }


}
