//
// ScmRepositoryRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ScmRepositoryRelationships: Codable {

    public var scmProvider: ScmRepositoryRelationshipsScmProvider?
    public var defaultBranch: CiBuildRunRelationshipsSourceBranchOrTag?

    public init(scmProvider: ScmRepositoryRelationshipsScmProvider? = nil, defaultBranch: CiBuildRunRelationshipsSourceBranchOrTag? = nil) {
        self.scmProvider = scmProvider
        self.defaultBranch = defaultBranch
    }


}
