//
// ScmRepositoryRelationshipsScmProvider.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ScmRepositoryRelationshipsScmProvider: Codable {

    public var links: AppCategoryRelationshipsSubcategoriesLinks?
    public var data: ScmRepositoryRelationshipsScmProviderData?

    public init(links: AppCategoryRelationshipsSubcategoriesLinks? = nil, data: ScmRepositoryRelationshipsScmProviderData? = nil) {
        self.links = links
        self.data = data
    }


}
