//
// SubscriptionGroupLocalizationUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubscriptionGroupLocalizationUpdateRequest: Codable {

    public var data: SubscriptionGroupLocalizationUpdateRequestData

    public init(data: SubscriptionGroupLocalizationUpdateRequestData) {
        self.data = data
    }


}
