//
// SubscriptionOfferCodeCustomCodeRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubscriptionOfferCodeCustomCodeRelationships: Codable {

    public var offerCode: SubscriptionOfferCodeCustomCodeRelationshipsOfferCode?

    public init(offerCode: SubscriptionOfferCodeCustomCodeRelationshipsOfferCode? = nil) {
        self.offerCode = offerCode
    }


}
