//
// SubscriptionPromotionalOfferPriceInlineCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubscriptionPromotionalOfferPriceInlineCreate: Codable {

    public enum ModelType: String, Codable { 
        case subscriptionpromotionalofferprices = "subscriptionPromotionalOfferPrices"
    }
    public var type: ModelType
    public var _id: String?
    public var relationships: SubscriptionOfferCodePriceInlineCreateRelationships?

    public init(type: ModelType, _id: String? = nil, relationships: SubscriptionOfferCodePriceInlineCreateRelationships? = nil) {
        self.type = type
        self._id = _id
        self.relationships = relationships
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case relationships
    }

}
