//
// SubscriptionOfferCodeOneTimeUseCodeCreateRequestData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubscriptionOfferCodeOneTimeUseCodeCreateRequestData: Codable {

    public enum ModelType: String, Codable { 
        case subscriptionoffercodeonetimeusecodes = "subscriptionOfferCodeOneTimeUseCodes"
    }
    public var type: ModelType
    public var attributes: SubscriptionOfferCodeOneTimeUseCodeCreateRequestDataAttributes
    public var relationships: SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships

    public init(type: ModelType, attributes: SubscriptionOfferCodeOneTimeUseCodeCreateRequestDataAttributes, relationships: SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships) {
        self.type = type
        self.attributes = attributes
        self.relationships = relationships
    }


}
