//
// SubscriptionCustomerEligibility.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum SubscriptionCustomerEligibility: String, Codable {
    case new = "NEW"
    case existing = "EXISTING"
    case expired = "EXPIRED"
}