//
// SubscriptionOfferCodeOneTimeUseCodeCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubscriptionOfferCodeOneTimeUseCodeCreateRequest: Codable {

    public var data: SubscriptionOfferCodeOneTimeUseCodeCreateRequestData

    public init(data: SubscriptionOfferCodeOneTimeUseCodeCreateRequestData) {
        self.data = data
    }


}
