//
// UserVisibleAppsLinkagesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserVisibleAppsLinkagesRequest: Codable {

    public var data: [AppClipRelationshipsAppData]

    public init(data: [AppClipRelationshipsAppData]) {
        self.data = data
    }


}
