//
// AppPreviewsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class AppPreviewsAPI {
    /**

     - parameter body: (body) AppPreview representation 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func appPreviewsCreateInstance(body: AppPreviewCreateRequest, completion: @escaping ((_ data: AppPreviewResponse?,_ error: Error?) -> Void)) {
        appPreviewsCreateInstanceWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /v1/appPreviews
     - 

     - :
       - type: http
       - name: itc-bearer-token
     - examples: [{contentType=application/json, example={
  "data" : {
    "relationships" : {
      "appPreviewSet" : {
        "data" : {
          "id" : "id",
          "type" : "appPreviewSets"
        },
        "links" : {
          "related" : "related",
          "self" : "self"
        }
      }
    },
    "attributes" : {
      "fileName" : "fileName",
      "videoUrl" : "videoUrl",
      "fileSize" : 0,
      "assetDeliveryState" : {
        "warnings" : [ null, null ],
        "state" : "AWAITING_UPLOAD",
        "errors" : [ {
          "code" : "code",
          "description" : "description"
        }, {
          "code" : "code",
          "description" : "description"
        } ]
      },
      "mimeType" : "mimeType",
      "sourceFileChecksum" : "sourceFileChecksum",
      "previewFrameTimeCode" : "previewFrameTimeCode",
      "uploadOperations" : [ {
        "requestHeaders" : [ {
          "name" : "name",
          "value" : "value"
        }, {
          "name" : "name",
          "value" : "value"
        } ],
        "method" : "method",
        "offset" : 5,
        "length" : 5,
        "url" : "url"
      }, {
        "requestHeaders" : [ {
          "name" : "name",
          "value" : "value"
        }, {
          "name" : "name",
          "value" : "value"
        } ],
        "method" : "method",
        "offset" : 5,
        "length" : 5,
        "url" : "url"
      } ],
      "previewImage" : {
        "width" : 6,
        "templateUrl" : "templateUrl",
        "height" : 1
      }
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "appPreviews"
  },
  "links" : {
    "self" : "self"
  },
  "included" : [ {
    "relationships" : {
      "appStoreVersionExperimentTreatmentLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionExperimentTreatmentLocalizations"
        }
      },
      "appCustomProductPageLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appCustomProductPageLocalizations"
        }
      },
      "appPreviews" : {
        "data" : [ {
          "id" : "id",
          "type" : "appPreviews"
        }, {
          "id" : "id",
          "type" : "appPreviews"
        } ],
        "meta" : {
          "paging" : {
            "total" : 0,
            "limit" : 6
          }
        }
      },
      "appStoreVersionLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionLocalizations"
        },
        "links" : {
          "related" : "related",
          "self" : "self"
        }
      }
    },
    "attributes" : {
      "previewType" : "IPHONE_65"
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "appPreviewSets"
  }, {
    "relationships" : {
      "appStoreVersionExperimentTreatmentLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionExperimentTreatmentLocalizations"
        }
      },
      "appCustomProductPageLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appCustomProductPageLocalizations"
        }
      },
      "appPreviews" : {
        "data" : [ {
          "id" : "id",
          "type" : "appPreviews"
        }, {
          "id" : "id",
          "type" : "appPreviews"
        } ],
        "meta" : {
          "paging" : {
            "total" : 0,
            "limit" : 6
          }
        }
      },
      "appStoreVersionLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionLocalizations"
        },
        "links" : {
          "related" : "related",
          "self" : "self"
        }
      }
    },
    "attributes" : {
      "previewType" : "IPHONE_65"
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "appPreviewSets"
  } ]
}}]
     - parameter body: (body) AppPreview representation 

     - returns: RequestBuilder<AppPreviewResponse> 
     */
    open class func appPreviewsCreateInstanceWithRequestBuilder(body: AppPreviewCreateRequest) -> RequestBuilder<AppPreviewResponse> {
        let path = "/v1/appPreviews"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<AppPreviewResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) the id of the requested resource 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func appPreviewsDeleteInstance(_id: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        appPreviewsDeleteInstanceWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /v1/appPreviews/{id}
     - 

     - :
       - type: http
       - name: itc-bearer-token
     - parameter _id: (path) the id of the requested resource 

     - returns: RequestBuilder<Void> 
     */
    open class func appPreviewsDeleteInstanceWithRequestBuilder(_id: String) -> RequestBuilder<Void> {
        var path = "/v1/appPreviews/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     * enum for parameter fieldsAppPreviews
     */
    public enum FieldsAppPreviews_appPreviewsGetInstance: String { 
        case apppreviewset = "appPreviewSet"
        case assetdeliverystate = "assetDeliveryState"
        case filename = "fileName"
        case filesize = "fileSize"
        case mimetype = "mimeType"
        case previewframetimecode = "previewFrameTimeCode"
        case previewimage = "previewImage"
        case sourcefilechecksum = "sourceFileChecksum"
        case uploadoperations = "uploadOperations"
        case uploaded = "uploaded"
        case videourl = "videoUrl"
    }

    /**
     * enum for parameter include
     */
    public enum Include_appPreviewsGetInstance: String { 
        case apppreviewset = "appPreviewSet"
    }

    /**

     - parameter _id: (path) the id of the requested resource 
     - parameter fieldsAppPreviews: (query) the fields to include for returned resources of type appPreviews (optional)
     - parameter include: (query) comma-separated list of relationships to include (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func appPreviewsGetInstance(_id: String, fieldsAppPreviews: [String]? = nil, include: [String]? = nil, completion: @escaping ((_ data: AppPreviewResponse?,_ error: Error?) -> Void)) {
        appPreviewsGetInstanceWithRequestBuilder(_id: _id, fieldsAppPreviews: fieldsAppPreviews, include: include).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/appPreviews/{id}
     - 

     - :
       - type: http
       - name: itc-bearer-token
     - examples: [{contentType=application/json, example={
  "data" : {
    "relationships" : {
      "appPreviewSet" : {
        "data" : {
          "id" : "id",
          "type" : "appPreviewSets"
        },
        "links" : {
          "related" : "related",
          "self" : "self"
        }
      }
    },
    "attributes" : {
      "fileName" : "fileName",
      "videoUrl" : "videoUrl",
      "fileSize" : 0,
      "assetDeliveryState" : {
        "warnings" : [ null, null ],
        "state" : "AWAITING_UPLOAD",
        "errors" : [ {
          "code" : "code",
          "description" : "description"
        }, {
          "code" : "code",
          "description" : "description"
        } ]
      },
      "mimeType" : "mimeType",
      "sourceFileChecksum" : "sourceFileChecksum",
      "previewFrameTimeCode" : "previewFrameTimeCode",
      "uploadOperations" : [ {
        "requestHeaders" : [ {
          "name" : "name",
          "value" : "value"
        }, {
          "name" : "name",
          "value" : "value"
        } ],
        "method" : "method",
        "offset" : 5,
        "length" : 5,
        "url" : "url"
      }, {
        "requestHeaders" : [ {
          "name" : "name",
          "value" : "value"
        }, {
          "name" : "name",
          "value" : "value"
        } ],
        "method" : "method",
        "offset" : 5,
        "length" : 5,
        "url" : "url"
      } ],
      "previewImage" : {
        "width" : 6,
        "templateUrl" : "templateUrl",
        "height" : 1
      }
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "appPreviews"
  },
  "links" : {
    "self" : "self"
  },
  "included" : [ {
    "relationships" : {
      "appStoreVersionExperimentTreatmentLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionExperimentTreatmentLocalizations"
        }
      },
      "appCustomProductPageLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appCustomProductPageLocalizations"
        }
      },
      "appPreviews" : {
        "data" : [ {
          "id" : "id",
          "type" : "appPreviews"
        }, {
          "id" : "id",
          "type" : "appPreviews"
        } ],
        "meta" : {
          "paging" : {
            "total" : 0,
            "limit" : 6
          }
        }
      },
      "appStoreVersionLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionLocalizations"
        },
        "links" : {
          "related" : "related",
          "self" : "self"
        }
      }
    },
    "attributes" : {
      "previewType" : "IPHONE_65"
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "appPreviewSets"
  }, {
    "relationships" : {
      "appStoreVersionExperimentTreatmentLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionExperimentTreatmentLocalizations"
        }
      },
      "appCustomProductPageLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appCustomProductPageLocalizations"
        }
      },
      "appPreviews" : {
        "data" : [ {
          "id" : "id",
          "type" : "appPreviews"
        }, {
          "id" : "id",
          "type" : "appPreviews"
        } ],
        "meta" : {
          "paging" : {
            "total" : 0,
            "limit" : 6
          }
        }
      },
      "appStoreVersionLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionLocalizations"
        },
        "links" : {
          "related" : "related",
          "self" : "self"
        }
      }
    },
    "attributes" : {
      "previewType" : "IPHONE_65"
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "appPreviewSets"
  } ]
}}]
     - parameter _id: (path) the id of the requested resource 
     - parameter fieldsAppPreviews: (query) the fields to include for returned resources of type appPreviews (optional)
     - parameter include: (query) comma-separated list of relationships to include (optional)

     - returns: RequestBuilder<AppPreviewResponse> 
     */
    open class func appPreviewsGetInstanceWithRequestBuilder(_id: String, fieldsAppPreviews: [String]? = nil, include: [String]? = nil) -> RequestBuilder<AppPreviewResponse> {
        var path = "/v1/appPreviews/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "fields[appPreviews]": fieldsAppPreviews, 
                        "include": include
        ])


        let requestBuilder: RequestBuilder<AppPreviewResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body) AppPreview representation 
     - parameter _id: (path) the id of the requested resource 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func appPreviewsUpdateInstance(body: AppPreviewUpdateRequest, _id: String, completion: @escaping ((_ data: AppPreviewResponse?,_ error: Error?) -> Void)) {
        appPreviewsUpdateInstanceWithRequestBuilder(body: body, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /v1/appPreviews/{id}
     - 

     - :
       - type: http
       - name: itc-bearer-token
     - examples: [{contentType=application/json, example={
  "data" : {
    "relationships" : {
      "appPreviewSet" : {
        "data" : {
          "id" : "id",
          "type" : "appPreviewSets"
        },
        "links" : {
          "related" : "related",
          "self" : "self"
        }
      }
    },
    "attributes" : {
      "fileName" : "fileName",
      "videoUrl" : "videoUrl",
      "fileSize" : 0,
      "assetDeliveryState" : {
        "warnings" : [ null, null ],
        "state" : "AWAITING_UPLOAD",
        "errors" : [ {
          "code" : "code",
          "description" : "description"
        }, {
          "code" : "code",
          "description" : "description"
        } ]
      },
      "mimeType" : "mimeType",
      "sourceFileChecksum" : "sourceFileChecksum",
      "previewFrameTimeCode" : "previewFrameTimeCode",
      "uploadOperations" : [ {
        "requestHeaders" : [ {
          "name" : "name",
          "value" : "value"
        }, {
          "name" : "name",
          "value" : "value"
        } ],
        "method" : "method",
        "offset" : 5,
        "length" : 5,
        "url" : "url"
      }, {
        "requestHeaders" : [ {
          "name" : "name",
          "value" : "value"
        }, {
          "name" : "name",
          "value" : "value"
        } ],
        "method" : "method",
        "offset" : 5,
        "length" : 5,
        "url" : "url"
      } ],
      "previewImage" : {
        "width" : 6,
        "templateUrl" : "templateUrl",
        "height" : 1
      }
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "appPreviews"
  },
  "links" : {
    "self" : "self"
  },
  "included" : [ {
    "relationships" : {
      "appStoreVersionExperimentTreatmentLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionExperimentTreatmentLocalizations"
        }
      },
      "appCustomProductPageLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appCustomProductPageLocalizations"
        }
      },
      "appPreviews" : {
        "data" : [ {
          "id" : "id",
          "type" : "appPreviews"
        }, {
          "id" : "id",
          "type" : "appPreviews"
        } ],
        "meta" : {
          "paging" : {
            "total" : 0,
            "limit" : 6
          }
        }
      },
      "appStoreVersionLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionLocalizations"
        },
        "links" : {
          "related" : "related",
          "self" : "self"
        }
      }
    },
    "attributes" : {
      "previewType" : "IPHONE_65"
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "appPreviewSets"
  }, {
    "relationships" : {
      "appStoreVersionExperimentTreatmentLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionExperimentTreatmentLocalizations"
        }
      },
      "appCustomProductPageLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appCustomProductPageLocalizations"
        }
      },
      "appPreviews" : {
        "data" : [ {
          "id" : "id",
          "type" : "appPreviews"
        }, {
          "id" : "id",
          "type" : "appPreviews"
        } ],
        "meta" : {
          "paging" : {
            "total" : 0,
            "limit" : 6
          }
        }
      },
      "appStoreVersionLocalization" : {
        "data" : {
          "id" : "id",
          "type" : "appStoreVersionLocalizations"
        },
        "links" : {
          "related" : "related",
          "self" : "self"
        }
      }
    },
    "attributes" : {
      "previewType" : "IPHONE_65"
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "appPreviewSets"
  } ]
}}]
     - parameter body: (body) AppPreview representation 
     - parameter _id: (path) the id of the requested resource 

     - returns: RequestBuilder<AppPreviewResponse> 
     */
    open class func appPreviewsUpdateInstanceWithRequestBuilder(body: AppPreviewUpdateRequest, _id: String) -> RequestBuilder<AppPreviewResponse> {
        var path = "/v1/appPreviews/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<AppPreviewResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
