//
// SubscriptionGracePeriodsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SubscriptionGracePeriodsAPI {
    /**
     * enum for parameter fieldsSubscriptionGracePeriods
     */
    public enum FieldsSubscriptionGracePeriods_subscriptionGracePeriodsGetInstance: String { 
        case app = "app"
        case optin = "optIn"
    }

    /**

     - parameter _id: (path) the id of the requested resource 
     - parameter fieldsSubscriptionGracePeriods: (query) the fields to include for returned resources of type subscriptionGracePeriods (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func subscriptionGracePeriodsGetInstance(_id: String, fieldsSubscriptionGracePeriods: [String]? = nil, completion: @escaping ((_ data: SubscriptionGracePeriodResponse?,_ error: Error?) -> Void)) {
        subscriptionGracePeriodsGetInstanceWithRequestBuilder(_id: _id, fieldsSubscriptionGracePeriods: fieldsSubscriptionGracePeriods).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/subscriptionGracePeriods/{id}
     - 

     - :
       - type: http
       - name: itc-bearer-token
     - examples: [{contentType=application/json, example={
  "data" : {
    "attributes" : {
      "optIn" : true
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "subscriptionGracePeriods"
  },
  "links" : {
    "self" : "self"
  }
}}]
     - parameter _id: (path) the id of the requested resource 
     - parameter fieldsSubscriptionGracePeriods: (query) the fields to include for returned resources of type subscriptionGracePeriods (optional)

     - returns: RequestBuilder<SubscriptionGracePeriodResponse> 
     */
    open class func subscriptionGracePeriodsGetInstanceWithRequestBuilder(_id: String, fieldsSubscriptionGracePeriods: [String]? = nil) -> RequestBuilder<SubscriptionGracePeriodResponse> {
        var path = "/v1/subscriptionGracePeriods/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "fields[subscriptionGracePeriods]": fieldsSubscriptionGracePeriods
        ])


        let requestBuilder: RequestBuilder<SubscriptionGracePeriodResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body) SubscriptionGracePeriod representation 
     - parameter _id: (path) the id of the requested resource 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func subscriptionGracePeriodsUpdateInstance(body: SubscriptionGracePeriodUpdateRequest, _id: String, completion: @escaping ((_ data: SubscriptionGracePeriodResponse?,_ error: Error?) -> Void)) {
        subscriptionGracePeriodsUpdateInstanceWithRequestBuilder(body: body, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /v1/subscriptionGracePeriods/{id}
     - 

     - :
       - type: http
       - name: itc-bearer-token
     - examples: [{contentType=application/json, example={
  "data" : {
    "attributes" : {
      "optIn" : true
    },
    "links" : {
      "self" : "self"
    },
    "id" : "id",
    "type" : "subscriptionGracePeriods"
  },
  "links" : {
    "self" : "self"
  }
}}]
     - parameter body: (body) SubscriptionGracePeriod representation 
     - parameter _id: (path) the id of the requested resource 

     - returns: RequestBuilder<SubscriptionGracePeriodResponse> 
     */
    open class func subscriptionGracePeriodsUpdateInstanceWithRequestBuilder(body: SubscriptionGracePeriodUpdateRequest, _id: String) -> RequestBuilder<SubscriptionGracePeriodResponse> {
        var path = "/v1/subscriptionGracePeriods/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SubscriptionGracePeriodResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
